Django/website/blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'  # creates a namespace for this app
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),

    path('post/create', views.create_post, name='create_post'),
    path('post/<int:post_id>', views.view_post, name='view_post'),
    path('post/', views.list_posts, name='list_posts'),
]

Django/website/website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),    
]

Django/website/blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from blog.models import User, Post
from django.forms import ModelForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import make_password, check_password


def index(request):
    if request.session.get("user", None):
        return HttpResponseRedirect(reverse("blog:list_posts"))
    return HttpResponseRedirect(reverse("blog:login"))


# https://stackoverflow.com/a/43793754
def login(request):
    errors = None
    if request.POST:
        # Create a model instance and populate it with data from the request
        uname = request.POST["username"]
        pwd = request.POST["password"]
        user = User.objects.filter(username=uname)

        if len(user) > 0 and check_password(pwd, user[0].password):
            # create a new session
            request.session["user"] = uname
            return HttpResponseRedirect(reverse('blog:list_posts'))
        else:
            errors = [('authentication', "Login error")]

    return render(request, 'blog/login.html', {'errors': errors})


### This version below has SQL Injection. To exploit:
# username: ' OR 1=1; --
# password: anything
### This will bypass the authentication
# def login(request):
#     errors = None
#     if request.POST:
#         # Create a model instance and populate it with data from the request
#         uname = request.POST["username"]
#         pwd = request.POST["password"]
#         hashed_password = make_password(pwd)
#         user = User.objects.raw(f"SELECT * FROM blog_user WHERE username='{uname}' AND password='{hashed_password}'")
#         if len(user) > 0:
#             # create a new session
#             request.session["user"] = uname
#             return HttpResponseRedirect(reverse('blog:list_posts'))
#         else:
#             errors = [('authentication', "Login error")]
#
#     return render(request, 'blog/login.html', {'errors': errors})
### End of SQL Injection


def logout(request):
    # remove the logged-in user information
    del request.session["user"]
    return HttpResponseRedirect(reverse("blog:login"))


def register(request):
    errors = None
    if request.POST:
        # Create a model instance and populate it with data from the request
        uname = request.POST["username"]
        pwd = request.POST["password"]
        email = request.POST["email"]

        user = User(username=uname, password=pwd, email=email)

        try:
            user.full_clean()
            user.password = make_password(pwd)  # encrypts
            # if we reach here, the validation succeeded
            user.save()  # saves on the db
            # redirect to the login page
            return HttpResponseRedirect(reverse('blog:login'))
        except ValidationError as e:
            errors = e

    return render(request, 'blog/register.html', {'errors': errors})


def list_posts(request):
    context = {
        "posts": Post.objects.all()
    }
    return render(request, 'blog/list.html', context)


def create_post(request):
    errors = None
    if request.POST:
        # make sure it is authenticated
        if request.session.get("user", None):
            # Create a model instance and populate it with data from the request
            title = request.POST["title"]
            content = request.POST["content"]
            user = User.objects.filter(username=request.session["user"])[0]
            try:
                post = Post(creator=user, title=title, content=content)
                post.save()  # if we reach here, the validation succeeded
                # redirect to the view posts page
                return HttpResponseRedirect(reverse('blog:list_posts'))
            except ValidationError as e:
                errors = e
        else:
            errors = [("authentication", "Only an authenticated user can create posts")]
    return render(request, 'blog/create.html', {'errors': errors})


def view_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/view.html', {'post': post})

Django/website/blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
        html, body {
            height: 100%;
            align-items: center;
            padding: 40px;
            background-color: #f5f5f5;
            text-align: center;
        }

        input {
            margin: 10px 0px;
        }
    </style>
</head>

<body>
{% if request.session.user %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'blog:logout' %}">Logout</a>
</nav>
{% endif %}
{% block body_content %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
</body>
</html>

Django/website/blog/templates/blog/create.html
{% extends "blog/base.html" %}
{% block body_content %}
<h1>User account profile creation</h1>
{% if errors %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
    <ul>
        {% for error in errors %}
        <li> {{ error.0 }}: {{error.1}}</li>
        {% endfor %}
    </ul>
</div>

{% endif %}
<form class="m-auto col-md-3" method="POST" action="{% url 'blog:create_post' %}">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Post information</h1>
    <div class="form-floating">
        <input type="text" class="form-control" id="title" name="title" placeholder="Title">
        <label for="title">Title</label>
    </div>
    <div class="form-floating">
        <textarea type="textarea" class="form-control" id="content" name="content"  rows="8">
        </textarea>
        <label for="content">Content</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Publish</button>
</form>
{% endblock %}

Django/website/blog/templates/blog/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Blog app ({{course}} -- {{semester}})</title>
    </head>
    <body>
        Hello World!
    </body>
</html>

Django/website/blog/templates/blog/list.html
{% extends "blog/base.html" %}
{% block body_content %}
<h1>Blog posts</h1>

<div class="container-fluid">
    {% if posts %}
    <ul>
        {% for post in posts %}
            <li>
                <a href="{% url 'blog:view_post' post.id %}">{{ post.title }}</a>
                (written by: <i>{{post.creator.username}}</i>)
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <i>No posts</i>
    {%endif%}
</div>

{% endblock %}

Django/website/blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% block body_content %}
<h1>User login</h1>
{% if errors %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
    <ul>
        {% for error in errors %}
        <li> {{ error.0 }}: {{error.1}}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<form class="m-auto col-md-3" method="POST">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
    <div class="form-floating">
        <input type="text" class="form-control" id="username" name="username" placeholder="username">
        <label for="username">Username</label>
    </div>
    <div class="form-floating">
        <input type="password" class="form-control" id="password" name="password"  placeholder="Password">
        <label for="password">Password</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
</form>
<p>Click <a href="{% url 'blog:register' %}">here to sign up</a></p>
{% endblock %}

Django/website/blog/templates/blog/register.html
{% extends "blog/base.html" %}
{% block body_content %}
<h1>User account profile creation</h1>
{% if errors %}
<div class="alert alert-danger d-flex align-items-center" role="alert">
    <ul>
        {% for error in errors %}
        <li> {{ error.0 }}: {{error.1}} </li>
        {% endfor %}
    </ul>
</div>

{% endif %}
<form class="m-auto col-md-3" method="POST">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Account information</h1>
    <div class="form-floating">
        <input type="text" class="form-control" id="username" name="username" placeholder="username">
        <label for="username">Username</label>
    </div>
    <div class="form-floating">
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        <label for="password">Password</label>
    </div>
    <div class="form-floating">
        <input type="email" class="form-control" id="email" name="email" placeholder="placeholder@example.com">
        <label for="email">E-mail</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
</form>
{% endblock %}

Django/website/blog/templates/blog/view.html
{% extends "blog/base.html" %}
{% block body_content %}

<h1>{{post.title}}</h1>
<div class="container-fluid">
    {{post.content}}
</div>

{% endblock %}